### PR TITLE
Event message track sample files m59640.

### PR DESCRIPTION
**Pull request by podborski**
~2 files are not yet added (only their metadata).~ 
It would be desirable to reduce the file size.

### CODE REVIEW

**Comment by podborski** [comment]
https://git.mpeg.expert/MPEG/Systems/FileFormat/isobmff/-/issues/329

**Comment by DenizUgur** [comment]
As with any associated files, we add them to the relevant conformance files. If you don't want do deal with them, add their glob pattern to `data/.cfignore`. We get a warning for ignored files so they won't be lost.

**Comment by podborski** [comment]
@DenizUgur do you mind adding these 2 files?

**Comment by DenizUgur** [comment]
@podborski here you go, ready for merge

**Pull request merged**
