### PR TITLE
Deprecated boxes support

### LINKED ISSUE #72: Handling deprecated 4CCs
### Summary

Some 4CCs have been deprecated (e.g. `mere`) but those are still registered at mp4ra (and this will stay like that). Some of those appear in this warning message:

```shell
2023-09-06 13:55:56.465 | WARNING  | construct.boxes:main:336 - Missing boxes in standard features (126): {'auvd', 'feci', 'heic', 'mjpg', 'mint', 'mp4a', 'nclx', 'auxv', 'mp7b', 'geom', 'Exif', 'cdec', 'ecam', 'heix', 'prof', 'isob', 'rICC', 'tile', 'lhti', 'lhte', '1pic', 'sdhd', 'spsc', 'icam', 'vvis', 'iovl', 'vvic', 'evmi', 'relo', 'iphd', 'hvci', 'ochd', 'heis', 'hvti', 'vide', 'iso4', 'mtyp', 'mime', 'pict', 'mif2', 'jpeg', 'levl', 'ctab', 'slid', 'spvi', 'eroi', 'vwsc', 'frar', 'hvce', 'odhd', 'iden', 'null', 'plvi', 'tesc', 'ilvi', 'clip', 'iso2', 'comp', 'jpgs', 'isom', 'm4ae', 'unif', 'rgan', 'mp41', 'mp42', 'isoa', 'scsz', 'm7hd', 'evir', 'vvhd', 'hevs', 'iso9', 'mp4v', 'heim', 'rtvi', 'soun', 'iso3', 'hevm', 'bitr', 'ipmc', 'cgsc', 'iso8', 'load', 'evm1', 'avci', 'hevx', 'matt', 'mere', 'nvws', 'mask', 'avcs', 'volv', 'mp7t', 'mp4s', 'msf1', 'evbi', 'evms', 'mjhd', 'iso6', 'pnot', 'kmat', 'mski', 'aSEI', 'iso7', 'mp71', 'fgsc', 'hvcx', 'resc', 'mif1', 'meco', 'iso5', 'iods', 'isoc', 'hevc', 'mela', 'prfl', 'imif', 'evbs', 'nras', 'crgn', 'imap', 'mpsz', 'esds', 'crhd', 'elvi', 'hapt'}
```

we need a way to deal with deprecated ones. Perhaps adding an optional `deprecated` flag to json files would be an option.

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by DenizUgur**
fixes #72

The support for deprecated boxes has been added. When all deprecated boxes are added to this PR we can merge it.

### CODE REVIEW

**Review by podborski — APPROVED** [review]
LGTM

**Comment by podborski** [comment]
@cconcolato do you see any deprecated boxes in this list? (note that a lot of those below are brands / handlers and they are already handled in other 2 PRs, but if you see any deprecated ones we should try to add them in this PR if possible.

> 2023-10-18 16:35:15.204 | WARNING  | construct.boxes:main:365 - Missing boxes in standard features (122): ['1pic', 'Exif', 'aSEI', 'auvd', 'auxv', 'avci', 'avcs', 'bitr', 'cdec', 'cgsc', 'clip', 'comp', 'crgn', 'crhd', 'ctab', 'ecam', 'elvi', 'eroi', 'esds', 'evbi', 'evbs', 'evir', 'evm1', 'evmi', 'evms', 'feci', 'fgsc', 'frar', 'geom', 'hapt', 'heic', 'heim', 'heis', 'heix', 'hevc', 'hevm', 'hevs', 'hevx', 'hvce', 'hvci', 'hvcx', 'hvti', 'icam', 'iden', 'ilvi', 'imap', 'iods', 'iovl', 'iphd', 'iso2', 'iso3', 'iso4', 'iso5', 'iso6', 'iso7', 'iso8', 'iso9', 'isoa', 'isob', 'isoc', 'isom', 'jpeg', 'jpgs', 'kmat', 'levl', 'lhte', 'lhti', 'load', 'm4ae', 'm7hd', 'mask', 'matt', 'mela', 'mif1', 'mif2', 'mime', 'mint', 'mjhd', 'mjpg', 'mp41', 'mp42', 'mp4a', 'mp4s', 'mp4v', 'mp71', 'mp7b', 'mp7t', 'mpsz', 'msf1', 'mski', 'mtyp', 'nclx', 'nras', 'null', 'nvws', 'ochd', 'odhd', 'pict', 'plvi', 'pnot', 'prfl', 'prof', 'rICC', 'relo', 'resc', 'rgan', 'rtvi', 'scsz', 'sdhd', 'slid', 'soun', 'spsc', 'spvi', 'tesc', 'tile', 'unif', 'vide', 'volv', 'vvhd', 'vvic', 'vvis', 'vwsc']

I added the deprecated from ISOBMFF in [c955f41](https://github.com/MPEGGroup/FileFormatConformance/pull/106/commits/c955f41e8483ed68b903aa6f72a9b51a4f445238) but didn't check others.

**Comment by podborski** [comment]
we should also incorporate the outcome of https://github.com/MPEGGroup/FileFormat/issues/47 I believe we can remove:

```json
{
      "fourcc": "svop",
      "description": "SVC dependency range",
      "containers": ["sgpd"],
      "type": "Box",
      "syntax": "class SVCDependencyRangeBox extends Box('svop') {\n\tunsigned int(3) min_dependency_id;\n\tunsigned int(3) min_temporal_id;\n\tbit(6) reserved = 0;\n\tunsigned int(4) min_quality_id;\n\tunsigned int(3) max_dependency_id;\n\tunsigned int(3) max_temporal_id;\n\tbit(6) reserved = 0;\n\tunsigned int(4) max_quality_id;\n}"
    },
```

as we already have:

```json
{
      "fourcc": "svdr",
      "description": "SVC dependency range",
      "containers": ["scif"],
      "type": "Box",
      "syntax": "class SVCDependencyRangeBox extends Box('svdr') {\n\tunsigned int(3) min_dependency_id;\n\tunsigned int(3) min_temporal_id;\n\tbit(6) reserved = 0;\n\tunsigned int(4) min_quality_id;\n\tunsigned int(3) max_dependency_id;\n\tunsigned int(3) max_temporal_id;\n\tbit(6) reserved = 0;\n\tunsigned int(4) max_quality_id;\n}"
    },
```

**Comment by DenizUgur** [comment]
Should we deprecate it instead of removing?

**Comment by podborski** [comment]
> Should we deprecate it instead of removing?

no, this was added by mistake. I believe it was a typo in the spec

**Comment by DenizUgur** [comment]
> we should also incorporate the outcome of https://github.com/MPEGGroup/FileFormat/issues/47 I believe we can remove:

>       "fourcc": "svop",


Is this related to #67?

**Comment by DenizUgur** [comment]
@podborski Should we merge this or would you like to keep it open to add all the deprecated boxes?

**Pull request merged**
