### PR TITLE
add VVC files from Nokia based on m56817,m57436,m58142

### PR DESCRIPTION
**Pull request by podborski**

### CODE REVIEW

**Comment by cconcolato** [comment]
We need to check that it covers:
m59495 [14496-15] VVC in 14496-15 conformance test vectors update

**Comment by cconcolato** [comment]
Fraunhofer HHI to confirm if they can review these files.

**Comment by cconcolato** [comment]
We need to update the database to include the missing flags that block the build.

**Comment by podborski** [comment]
> @podborski, we need to add names for each flag. If you could share the link to the spec, I can do it.

done

**Pull request merged**
