### PR TITLE
add files from m64279. isobmff/nalu updates. Telecom Paris / Canon

### PR DESCRIPTION
**Pull request by podborski**

### CODE REVIEW

**Comment by cconcolato** [comment]
Netflix will review the sample groups.
Apple will review the single layer files.
Nokia will review the extractor files.
We still need reviewers for tiles and implicit reconstruction.

**Comment by DenizUgur** [comment]
@cconcolato As pointed out in #90 by @podborski, are we sure `0xA9` is a valid character in a fourcc?

**Comment by cconcolato** [comment]
> @cconcolato As pointed out in #90 by @podborski, are we sure `0xA9` is a valid character in a fourcc?

QuickTime often uses interesting characters.

@jeanlf fixed the output to use UTF-8.

**Comment by DenizUgur** [comment]
Yeah he did, although the automations we have still checks if the character is within `[0x20, 0x7E]` range as per the quote in #90.

**Comment by cconcolato** [comment]
> Yeah he did, although the automations we have still checks if the character is within `[0x20, 0x7E]` range as per the quote in #90.

The quote says "can be expressed as four characters from the range 0020 to 007E, inclusive" it is not a SHALL.

**Comment by DenizUgur** [comment]
fixed in eb2afba7acf7ed99050f5e034cd09a8f8d6163d6

**Pull request merged**
