### PR TITLE
add files from m63203. HEIF region items. Canon

### PR DESCRIPTION
**Pull request by podborski**
Note that the contribution [m63203](https://dms.mpeg.expert/doc_end_user/documents/142_Antalya/wg11/m63203-v2-m63203_HEIF_rgan_item_conformance_v2.zip) has more dumps that can be used to finalize this PR.

### CODE REVIEW

**Comment by cconcolato** [comment]
Reviewers needed.

**Comment by fmaze** [comment]
From discussion in [GitHub#82](https://github.com/MPEGGroup/FileFormat/issues/82) it would appear that at least the region-polygon.heic example is currently invalid.  

The region-polygon.heic example has Item 2 -[cdsc]-> Item 100, and Item 100 -[cdsc]-> Item 1 where Item 1 and 2 are `'hvc1'` and Item 100 is `'rgan'`.  

But, we should rather have **Item 100 -[eroi]-> Item 2**, and Item 100 -[cdsc]-> Item 1.  

In 23008-12 2nd ed. clause 6.10.3, (and future update in latest draft of 23008-12 2nd ed. FDAM1 clause 11.3.1), it is stated that region item `rgan` is associated with:  
- "metadata items, using an item reference of type `'cdsc'` from the metadata item to the region item"  
- "image items (...), using an item reference of type `'eroi'` from the region item to the image item (...)"

**Comment by bradh** [comment]
There are definitely more examples in this PR where there is an `[image] -[cdsc]-> [rgan item]` reference. For example, the region-rectangle.heic appears the same.

**Comment by podborski** [comment]
This PR is replaced with #137

**Pull request closed without merging**
